version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development  # Example environment variable, adjust as needed

  backend: 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"  #external:internal
    environment:
      - NODE_ENV=development  # Example, adjust according to your backend needs
    # Optionally, add volumes for the backend if you have live reloading set up there too
